### ISSUE TITLE
references to ResponseHeader classes missing "." after "Models"

### ISSUE THREAD

**Issue by baralong** [mulesoft/amf-dotnet-tools#2]
I downloaded the RAML ZIP file from our private API and uploaded into the tool to generate code, then compiled.

I found that when the generated code  referenced ResponseHeader classes it was missing the "." after the model e.g.
```c#
    var headers = new my.namespace.Api.ModelsPostMeasurementDocSystemCreatedResponseHeader();
```
should have been 
```c#
    var headers = new my.namespace.Api.Models.PostMeasurementDocSystemCreatedResponseHeader();
```

and 

```c#
    public my.namespace.Api.ModelsPostMeasurementDocCreatedResponseHeader Headers { get; set; }
```
should have been 
```c#
    public my.namespace.Api.Models.PostMeasurementDocCreatedResponseHeader Headers { get; set; }
```

The source files for the generation are zipped here [rtbs-pm-sapi-1.0.21-raml.zip](https://github.com/mulesoft/amf-dotnet-tools/files/3164967/rtbs-pm-sapi-1.0.21-raml.zip)

**Comment by woodp** [comment]
fixed in release v0.02-beta
