### ISSUE TITLE
Optional query parameters were not generated as nullable 

### ISSUE THREAD

**Issue by baralong** [mulesoft/amf-dotnet-tools#3]
Optional parameters for some `Get` methods were not generated as nullable, however the code referencing them checked for null resulting in a warning of ["CS0472"](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0472)

e.g.
```c#
if(getfunctionallocationsflidnotificationsquery.Limit != null)
    url += "&Limit=" + getfunctionallocationsflidnotificationsquery.Limit;
```
and limit is defined as:
```c#
public decimal Limit { get; set; }
```

The source files for the generation are zipped here [rtbs-pm-sapi-1.0.21-raml.zip](https://github.com/mulesoft/amf-dotnet-tools/files/3164967/rtbs-pm-sapi-1.0.21-raml.zip)

**Comment by woodp** [comment]
this is resolved and will be available in the next release, please check the new repo at:  https://github.com/mulesoft-labs/raml-dotnet-tools
