### ISSUE TITLE
Can only connect to anypoint via basic authentication

### ISSUE THREAD

**Issue by baralong** [mulesoft/amf-dotnet-tools#4]
We connect to anypoint.mulesoft.com using out our Office 365 accounts. The amf-tool only lets us log in via basic authentication, i.e. username & password.

The workaround is to download the raml zip file then unzip and upload into the tool.

**Comment by woodp** [comment]
please move this request to the new repo at:  https://github.com/mulesoft-labs/raml-dotnet-tools
