### ISSUE TITLE
Question: Is there any way to use snake_case for JSON?

### ISSUE THREAD

**Issue by microshine** [mulesoft/amf-dotnet-tools#6]
I need to send (and get) JSON objects with snake_case properties

### JSON example
```json
{
  "user_login": "login",
  "user_password": "password"
}
```

amf.tools generates CS like this
```cs
public class LoginPost {
  public string UserLogin { get; set; }
  public string UserPassword { get; set; }
}
```

### AMF.tools serialized JSON
```json
{
  "UserLogin": "login",
  "UserPassword": "password"
}
```
I've got PascalCase only. 
How can I solve it using amf.tools?
Is it possible to use a custom name for the property (eg [JsonPropertyAttribute](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonPropertyAttribute.htm))?

**Comment by woodp** [comment]
hi @microshine, sorry for the delay in answering. 
New version generates the properties with the "_". And also captures the original name and uses it to add a JsonPropertyAttribute when is different than the generated property. 
But I just tested it and there's still a problem on the new version. Will be fixing it for the next one.
Newer version of the tool will be published here: https://github.com/mulesoft-labs/raml-dotnet-tools/releases

**Comment by woodp** [comment]
new preview version: https://marketplace.visualstudio.com/items?itemName=MuleSoftInc.RAMLToolsforNET
has this fixed.
If you have any issues please add them in the new repo: https://github.com/mulesoft-labs/raml-dotnet-tools
